/* tslint:disable */
/* eslint-disable */
/**
 * This file was automatically generated by Payload.
 * DO NOT MODIFY IT BY HAND. Instead, modify your source Payload config,
 * and re-run `payload generate:types` to regenerate this file.
 */

/**
 * Supported timezones in IANA format.
 *
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "supportedTimezones".
 */
export type SupportedTimezones =
  | 'Pacific/Midway'
  | 'Pacific/Niue'
  | 'Pacific/Honolulu'
  | 'Pacific/Rarotonga'
  | 'America/Anchorage'
  | 'Pacific/Gambier'
  | 'America/Los_Angeles'
  | 'America/Tijuana'
  | 'America/Denver'
  | 'America/Phoenix'
  | 'America/Chicago'
  | 'America/Guatemala'
  | 'America/New_York'
  | 'America/Bogota'
  | 'America/Caracas'
  | 'America/Santiago'
  | 'America/Buenos_Aires'
  | 'America/Sao_Paulo'
  | 'Atlantic/South_Georgia'
  | 'Atlantic/Azores'
  | 'Atlantic/Cape_Verde'
  | 'Europe/London'
  | 'Europe/Berlin'
  | 'Africa/Lagos'
  | 'Europe/Athens'
  | 'Africa/Cairo'
  | 'Europe/Moscow'
  | 'Asia/Riyadh'
  | 'Asia/Dubai'
  | 'Asia/Baku'
  | 'Asia/Karachi'
  | 'Asia/Tashkent'
  | 'Asia/Calcutta'
  | 'Asia/Dhaka'
  | 'Asia/Almaty'
  | 'Asia/Jakarta'
  | 'Asia/Bangkok'
  | 'Asia/Shanghai'
  | 'Asia/Singapore'
  | 'Asia/Tokyo'
  | 'Asia/Seoul'
  | 'Australia/Brisbane'
  | 'Australia/Sydney'
  | 'Pacific/Guam'
  | 'Pacific/Noumea'
  | 'Pacific/Auckland'
  | 'Pacific/Fiji';

export interface Config {
  auth: {
    users: UserAuthOperations;
  };
  blocks: {};
  collections: {
    schools: School;
    users: User;
    'payload-kv': PayloadKv;
    'payload-locked-documents': PayloadLockedDocument;
    'payload-preferences': PayloadPreference;
    'payload-migrations': PayloadMigration;
  };
  collectionsJoins: {};
  collectionsSelect: {
    schools: SchoolsSelect<false> | SchoolsSelect<true>;
    users: UsersSelect<false> | UsersSelect<true>;
    'payload-kv': PayloadKvSelect<false> | PayloadKvSelect<true>;
    'payload-locked-documents': PayloadLockedDocumentsSelect<false> | PayloadLockedDocumentsSelect<true>;
    'payload-preferences': PayloadPreferencesSelect<false> | PayloadPreferencesSelect<true>;
    'payload-migrations': PayloadMigrationsSelect<false> | PayloadMigrationsSelect<true>;
  };
  db: {
    defaultIDType: number;
  };
  fallbackLocale: null;
  globals: {};
  globalsSelect: {};
  locale: null;
  widgets: {
    collections: CollectionsWidget;
  };
  user: User;
  jobs: {
    tasks: unknown;
    workflows: unknown;
  };
}
export interface UserAuthOperations {
  forgotPassword: {
    email: string;
    password: string;
  };
  login: {
    email: string;
    password: string;
  };
  registerFirstUser: {
    email: string;
    password: string;
  };
  unlock: {
    email: string;
    password: string;
  };
}
/**
 * Every school in the public directory. Changes go live once published.
 *
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "schools".
 */
export interface School {
  /**
   * Permanent identifier.
   */
  id: string;
  name: string;
  /**
   * The URL segment: /schools/<slug>. Changing it breaks existing links.
   */
  slug: string;
  level: 'primary' | 'secondary';
  /**
   * The school's own strapline, if it has one.
   */
  tagline?: string | null;
  /**
   * Shown as “About this school”. Write in the school's own words, in complete sentences.
   */
  summary?: string | null;
  /**
   * Stages offered, e.g. “Creche, Primary”.
   */
  scope?: string | null;
  yearFounded?: number | null;
  /**
   * British, Nigerian, Montessori, and so on.
   */
  curricula?: string[] | null;
  faith?: ('Secular' | 'Christian' | 'Islamic') | null;
  /**
   * Fixed list — pick the official spelling.
   */
  state?:
    | (
        | 'Abia'
        | 'Adamawa'
        | 'Akwa Ibom'
        | 'Anambra'
        | 'Bauchi'
        | 'Bayelsa'
        | 'Benue'
        | 'Borno'
        | 'Cross River'
        | 'Delta'
        | 'Ebonyi'
        | 'Edo'
        | 'Ekiti'
        | 'Enugu'
        | 'FCT (Abuja)'
        | 'Gombe'
        | 'Imo'
        | 'Jigawa'
        | 'Kaduna'
        | 'Kano'
        | 'Katsina'
        | 'Kebbi'
        | 'Kogi'
        | 'Kwara'
        | 'Lagos'
        | 'Nasarawa'
        | 'Niger'
        | 'Ogun'
        | 'Ondo'
        | 'Osun'
        | 'Oyo'
        | 'Plateau'
        | 'Rivers'
        | 'Sokoto'
        | 'Taraba'
        | 'Yobe'
        | 'Zamfara'
      )
    | null;
  /**
   * Town or district, e.g. Lekki.
   */
  area?: string | null;
  address?: string | null;
  /**
   * Nearest landmark or bus stop.
   */
  busStop?: string | null;
  /**
   * The school’s own line. Leave empty if unknown — never a directory or agency number.
   */
  phone?: string | null;
  /**
   * Named contact for admissions enquiries, e.g. “Ms Winnie Oragwu”. Shown beside the number so a parent knows who they are about to reach.
   */
  admissionsOfficer?: string | null;
  /**
   * That person’s role, e.g. “Admissions Manager”.
   */
  admissionsRole?: string | null;
  /**
   * Include https://
   */
  website?: string | null;
  /**
   * The headline band shown on cards and used by the budget filter.
   */
  fee?: {
    /**
     * As published, e.g. “N1 000 000+”.
     */
    label?: string | null;
    /**
     * Lower bound per term, in naira.
     */
    min?: number | null;
    /**
     * Upper bound per term. Leave empty for open-ended.
     */
    max?: number | null;
  };
  /**
   * Exact published tuition lines, where the school itemised them. More precise than the band above.
   */
  feeItems?:
    | {
        label: string;
        amount: number;
        id?: string | null;
      }[]
    | null;
  /**
   * What the school itself publishes, e.g. “Partial” or “Full”. Leave empty if it says nothing — an empty field reads as “not provided”, which is honest, whereas “not available” tells a parent the school offers none.
   */
  scholarship?: string | null;
  /**
   * As published, e.g. “5% off the third sibling”. Leave empty if unknown.
   */
  siblingsDiscount?: string | null;
  /**
   * Path or URL to a downloadable admission form.
   */
  admissionForm?: string | null;
  day?: boolean | null;
  boarding?: boolean | null;
  /**
   * Maximum pupils per class.
   */
  maxClassSize?: number | null;
  facilities?: string[] | null;
  activities?: string[] | null;
  clubs?: string[] | null;
  images?: {
    /**
     * Path to the school's logo.
     */
    logo?: string | null;
    gallery?:
      | {
          full: string;
          thumb: string;
          id?: string | null;
        }[]
      | null;
  };
  /**
   * Only tick this once someone has confirmed these details with the school directly. Never from the school's own website alone.
   */
  verified?: boolean | null;
  updatedAt: string;
  createdAt: string;
  _status?: ('draft' | 'published') | null;
}
/**
 * Accounts that can sign in. Passwords cannot be read back — set a new one here if somebody is locked out.
 *
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "users".
 */
export interface User {
  id: number;
  /**
   * Shown on records this person creates or edits.
   */
  name: string;
  /**
   * Editors manage content. Admins additionally mark schools as verified. Super admins additionally manage accounts and passwords.
   */
  role: 'super-admin' | 'admin' | 'editor';
  updatedAt: string;
  createdAt: string;
  email: string;
  resetPasswordToken?: string | null;
  resetPasswordExpiration?: string | null;
  salt?: string | null;
  hash?: string | null;
  loginAttempts?: number | null;
  lockUntil?: string | null;
  sessions?:
    | {
        id: string;
        createdAt?: string | null;
        expiresAt: string;
      }[]
    | null;
  password?: string | null;
  collection: 'users';
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "payload-kv".
 */
export interface PayloadKv {
  id: number;
  key: string;
  data:
    | {
        [k: string]: unknown;
      }
    | unknown[]
    | string
    | number
    | boolean
    | null;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "payload-locked-documents".
 */
export interface PayloadLockedDocument {
  id: number;
  document?:
    | ({
        relationTo: 'schools';
        value: string | School;
      } | null)
    | ({
        relationTo: 'users';
        value: number | User;
      } | null);
  globalSlug?: string | null;
  user: {
    relationTo: 'users';
    value: number | User;
  };
  updatedAt: string;
  createdAt: string;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "payload-preferences".
 */
export interface PayloadPreference {
  id: number;
  user: {
    relationTo: 'users';
    value: number | User;
  };
  key?: string | null;
  value?:
    | {
        [k: string]: unknown;
      }
    | unknown[]
    | string
    | number
    | boolean
    | null;
  updatedAt: string;
  createdAt: string;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "payload-migrations".
 */
export interface PayloadMigration {
  id: number;
  name?: string | null;
  batch?: number | null;
  updatedAt: string;
  createdAt: string;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "schools_select".
 */
export interface SchoolsSelect<T extends boolean = true> {
  id?: T;
  name?: T;
  slug?: T;
  level?: T;
  tagline?: T;
  summary?: T;
  scope?: T;
  yearFounded?: T;
  curricula?: T;
  faith?: T;
  state?: T;
  area?: T;
  address?: T;
  busStop?: T;
  phone?: T;
  admissionsOfficer?: T;
  admissionsRole?: T;
  website?: T;
  fee?:
    | T
    | {
        label?: T;
        min?: T;
        max?: T;
      };
  feeItems?:
    | T
    | {
        label?: T;
        amount?: T;
        id?: T;
      };
  scholarship?: T;
  siblingsDiscount?: T;
  admissionForm?: T;
  day?: T;
  boarding?: T;
  maxClassSize?: T;
  facilities?: T;
  activities?: T;
  clubs?: T;
  images?:
    | T
    | {
        logo?: T;
        gallery?:
          | T
          | {
              full?: T;
              thumb?: T;
              id?: T;
            };
      };
  verified?: T;
  updatedAt?: T;
  createdAt?: T;
  _status?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "users_select".
 */
export interface UsersSelect<T extends boolean = true> {
  name?: T;
  role?: T;
  updatedAt?: T;
  createdAt?: T;
  email?: T;
  resetPasswordToken?: T;
  resetPasswordExpiration?: T;
  salt?: T;
  hash?: T;
  loginAttempts?: T;
  lockUntil?: T;
  sessions?:
    | T
    | {
        id?: T;
        createdAt?: T;
        expiresAt?: T;
      };
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "payload-kv_select".
 */
export interface PayloadKvSelect<T extends boolean = true> {
  key?: T;
  data?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "payload-locked-documents_select".
 */
export interface PayloadLockedDocumentsSelect<T extends boolean = true> {
  document?: T;
  globalSlug?: T;
  user?: T;
  updatedAt?: T;
  createdAt?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "payload-preferences_select".
 */
export interface PayloadPreferencesSelect<T extends boolean = true> {
  user?: T;
  key?: T;
  value?: T;
  updatedAt?: T;
  createdAt?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "payload-migrations_select".
 */
export interface PayloadMigrationsSelect<T extends boolean = true> {
  name?: T;
  batch?: T;
  updatedAt?: T;
  createdAt?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "collections_widget".
 */
export interface CollectionsWidget {
  data?: {
    [k: string]: unknown;
  };
  width: 'full';
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "auth".
 */
export interface Auth {
  [k: string]: unknown;
}


declare module 'payload' {
  export interface GeneratedTypes extends Config {}
}