/* tslint:disable */
/* eslint-disable */
/**
 * This file was automatically generated by Payload.
 * DO NOT MODIFY IT BY HAND. Instead, modify your source Payload config,
 * and re-run `payload generate:types` to regenerate this file.
 */

/**
 * Supported timezones in IANA format.
 *
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "supportedTimezones".
 */
export type SupportedTimezones =
  | 'Pacific/Midway'
  | 'Pacific/Niue'
  | 'Pacific/Honolulu'
  | 'Pacific/Rarotonga'
  | 'America/Anchorage'
  | 'Pacific/Gambier'
  | 'America/Los_Angeles'
  | 'America/Tijuana'
  | 'America/Denver'
  | 'America/Phoenix'
  | 'America/Chicago'
  | 'America/Guatemala'
  | 'America/New_York'
  | 'America/Bogota'
  | 'America/Caracas'
  | 'America/Santiago'
  | 'America/Buenos_Aires'
  | 'America/Sao_Paulo'
  | 'Atlantic/South_Georgia'
  | 'Atlantic/Azores'
  | 'Atlantic/Cape_Verde'
  | 'Europe/London'
  | 'Europe/Berlin'
  | 'Africa/Lagos'
  | 'Europe/Athens'
  | 'Africa/Cairo'
  | 'Europe/Moscow'
  | 'Asia/Riyadh'
  | 'Asia/Dubai'
  | 'Asia/Baku'
  | 'Asia/Karachi'
  | 'Asia/Tashkent'
  | 'Asia/Calcutta'
  | 'Asia/Dhaka'
  | 'Asia/Almaty'
  | 'Asia/Jakarta'
  | 'Asia/Bangkok'
  | 'Asia/Shanghai'
  | 'Asia/Singapore'
  | 'Asia/Tokyo'
  | 'Asia/Seoul'
  | 'Australia/Brisbane'
  | 'Australia/Sydney'
  | 'Pacific/Guam'
  | 'Pacific/Noumea'
  | 'Pacific/Auckland'
  | 'Pacific/Fiji';

export interface Config {
  auth: {
    users: UserAuthOperations;
  };
  blocks: {};
  collections: {
    schools: School;
    'school-submissions': SchoolSubmission;
    'school-contacts': SchoolContact;
    users: User;
    events: Event;
    'access-links': AccessLink;
    'payload-kv': PayloadKv;
    'payload-locked-documents': PayloadLockedDocument;
    'payload-preferences': PayloadPreference;
    'payload-migrations': PayloadMigration;
  };
  collectionsJoins: {};
  collectionsSelect: {
    schools: SchoolsSelect<false> | SchoolsSelect<true>;
    'school-submissions': SchoolSubmissionsSelect<false> | SchoolSubmissionsSelect<true>;
    'school-contacts': SchoolContactsSelect<false> | SchoolContactsSelect<true>;
    users: UsersSelect<false> | UsersSelect<true>;
    events: EventsSelect<false> | EventsSelect<true>;
    'access-links': AccessLinksSelect<false> | AccessLinksSelect<true>;
    'payload-kv': PayloadKvSelect<false> | PayloadKvSelect<true>;
    'payload-locked-documents': PayloadLockedDocumentsSelect<false> | PayloadLockedDocumentsSelect<true>;
    'payload-preferences': PayloadPreferencesSelect<false> | PayloadPreferencesSelect<true>;
    'payload-migrations': PayloadMigrationsSelect<false> | PayloadMigrationsSelect<true>;
  };
  db: {
    defaultIDType: number;
  };
  fallbackLocale: null;
  globals: {
    'outreach-settings': OutreachSetting;
  };
  globalsSelect: {
    'outreach-settings': OutreachSettingsSelect<false> | OutreachSettingsSelect<true>;
  };
  locale: null;
  widgets: {
    collections: CollectionsWidget;
  };
  user: User;
  jobs: {
    tasks: unknown;
    workflows: unknown;
  };
}
export interface UserAuthOperations {
  forgotPassword: {
    email: string;
    password: string;
  };
  login: {
    email: string;
    password: string;
  };
  registerFirstUser: {
    email: string;
    password: string;
  };
  unlock: {
    email: string;
    password: string;
  };
}
/**
 * Every school in the public directory. Changes go live once published.
 *
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "schools".
 */
export interface School {
  /**
   * Permanent identifier.
   */
  id: string;
  name: string;
  /**
   * The URL segment: /schools/<slug>. Changing it breaks existing links.
   */
  slug: string;
  level: 'primary' | 'secondary';
  /**
   * The school's own strapline, if it has one.
   */
  tagline?: string | null;
  /**
   * Shown as “About this school”. Write in the school's own words, in complete sentences.
   */
  summary?: string | null;
  /**
   * Stages offered, e.g. “Creche, Primary”.
   */
  scope?: string | null;
  yearFounded?: number | null;
  /**
   * British, Nigerian, Montessori, and so on.
   */
  curricula?: string[] | null;
  faith?: ('Secular' | 'Christian' | 'Islamic') | null;
  /**
   * Fixed list — pick the official spelling.
   */
  state?:
    | (
        | 'Abia'
        | 'Adamawa'
        | 'Akwa Ibom'
        | 'Anambra'
        | 'Bauchi'
        | 'Bayelsa'
        | 'Benue'
        | 'Borno'
        | 'Cross River'
        | 'Delta'
        | 'Ebonyi'
        | 'Edo'
        | 'Ekiti'
        | 'Enugu'
        | 'FCT (Abuja)'
        | 'Gombe'
        | 'Imo'
        | 'Jigawa'
        | 'Kaduna'
        | 'Kano'
        | 'Katsina'
        | 'Kebbi'
        | 'Kogi'
        | 'Kwara'
        | 'Lagos'
        | 'Nasarawa'
        | 'Niger'
        | 'Ogun'
        | 'Ondo'
        | 'Osun'
        | 'Oyo'
        | 'Plateau'
        | 'Rivers'
        | 'Sokoto'
        | 'Taraba'
        | 'Yobe'
        | 'Zamfara'
      )
    | null;
  /**
   * Town or district, e.g. Lekki.
   */
  area?: string | null;
  address?: string | null;
  /**
   * Nearest landmark or bus stop.
   */
  busStop?: string | null;
  /**
   * The school’s own line. Leave empty if unknown — never a directory or agency number.
   */
  phone?: string | null;
  /**
   * The school’s own enquiry address. Leave empty if unknown — never a directory or agency address.
   */
  email?: string | null;
  /**
   * Named contact for admissions enquiries, e.g. “Ms Winnie Oragwu”. Shown beside the number so a parent knows who they are about to reach.
   */
  admissionsOfficer?: string | null;
  /**
   * That person’s role, e.g. “Admissions Manager”.
   */
  admissionsRole?: string | null;
  /**
   * Include https://
   */
  website?: string | null;
  /**
   * The headline band shown on cards and used by the budget filter.
   */
  fee?: {
    /**
     * As published, e.g. “N1 000 000+”.
     */
    label?: string | null;
    /**
     * Lower bound per term, in naira.
     */
    min?: number | null;
    /**
     * Upper bound per term. Leave empty for open-ended.
     */
    max?: number | null;
  };
  /**
   * Exact published tuition lines, where the school itemised them. More precise than the band above.
   */
  feeItems?:
    | {
        label: string;
        amount: number;
        id?: string | null;
      }[]
    | null;
  /**
   * What the school itself publishes, e.g. “Partial” or “Full”. Leave empty if it says nothing — an empty field reads as “not provided”, which is honest, whereas “not available” tells a parent the school offers none.
   */
  scholarship?: string | null;
  /**
   * As published, e.g. “5% off the third sibling”. Leave empty if unknown.
   */
  siblingsDiscount?: string | null;
  /**
   * Path or URL to a downloadable admission form.
   */
  admissionForm?: string | null;
  day?: boolean | null;
  boarding?: boolean | null;
  /**
   * Maximum pupils per class.
   */
  maxClassSize?: number | null;
  facilities?: string[] | null;
  activities?: string[] | null;
  clubs?: string[] | null;
  images?: {
    /**
     * Path to the school's logo.
     */
    logo?: string | null;
    gallery?:
      | {
          full: string;
          thumb: string;
          id?: string | null;
        }[]
      | null;
  };
  /**
   * Show in “Featured schools” on the home page. Only verified schools are featured; ticking this on an unverified school has no effect until it is verified.
   */
  featured?: boolean | null;
  /**
   * Only tick this once someone has confirmed these details with the school directly. Never from the school's own website alone.
   */
  verified?: boolean | null;
  updatedAt: string;
  createdAt: string;
  _status?: ('draft' | 'published') | null;
}
/**
 * Changes schools have sent in. Open one to compare it with the live listing, then set the status to Approved or Rejected and save.
 *
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "school-submissions".
 */
export interface SchoolSubmission {
  id: number;
  /**
   * Approving publishes these changes and marks the school verified.
   */
  status: 'pending' | 'approved' | 'rejected' | 'superseded';
  /**
   * For the team. Not sent to the school.
   */
  reviewNote?: string | null;
  kind: 'update' | 'confirm' | 'removal';
  school: string;
  schoolName?: string | null;
  schoolSlug?: string | null;
  contactName?: string | null;
  contactRole?: string | null;
  contactEmail?: string | null;
  /**
   * Anything the school wanted to tell us.
   */
  message?: string | null;
  changes?:
    | {
        [k: string]: unknown;
      }
    | unknown[]
    | string
    | number
    | boolean
    | null;
  before?:
    | {
        [k: string]: unknown;
      }
    | unknown[]
    | string
    | number
    | boolean
    | null;
  reviewedBy?: (number | null) | User;
  reviewedAt?: string | null;
  updatedAt: string;
  createdAt: string;
}
/**
 * Accounts that can sign in. Passwords cannot be read back — set a new one here if somebody is locked out.
 *
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "users".
 */
export interface User {
  id: number;
  /**
   * Shown on records this person creates or edits.
   */
  name: string;
  /**
   * Analysts read the dashboard and change nothing. Editors manage content. Admins additionally mark schools as verified. Super admins additionally manage accounts and passwords.
   */
  role: 'super-admin' | 'admin' | 'editor' | 'analyst';
  updatedAt: string;
  createdAt: string;
  email: string;
  resetPasswordToken?: string | null;
  resetPasswordExpiration?: string | null;
  salt?: string | null;
  hash?: string | null;
  loginAttempts?: number | null;
  lockUntil?: string | null;
  sessions?:
    | {
        id: string;
        createdAt?: string | null;
        expiresAt: string;
      }[]
    | null;
  password?: string | null;
  collection: 'users';
}
/**
 * Every school we have emailed, and how far it has got. Updated automatically.
 *
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "school-contacts".
 */
export interface SchoolContact {
  id: number;
  school: string;
  name?: string | null;
  email: string;
  status: 'none' | 'sent' | 'opened' | 'submitted' | 'approved';
  /**
   * Asked not to be emailed again. Never contacted while this is set.
   */
  optedOut?: boolean | null;
  sends?: number | null;
  firstSentAt?: string | null;
  lastSentAt?: string | null;
  /**
   * First time the link was opened. Some email security filters open links to scan them, so this can be early.
   */
  openedAt?: string | null;
  submittedAt?: string | null;
  updatedAt: string;
  createdAt: string;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "events".
 */
export interface Event {
  id: number;
  type: 'search' | 'view';
  /**
   * The page this happened on.
   */
  path?: string | null;
  /**
   * For a profile view, which school.
   */
  slug?: string | null;
  /**
   * For a search, what was typed. Lowercased and trimmed.
   */
  query?: string | null;
  /**
   * Filters applied alongside the query, as a readable summary.
   */
  filters?: string | null;
  /**
   * How many schools came back. Zero is the interesting case.
   */
  results?: number | null;
  /**
   * Hostname only, never the full URL — google.com, not the query.
   */
  referrer?: string | null;
  device?: ('phone' | 'tablet' | 'computer') | null;
  /**
   * A per-day anonymous token. Lets one person's three page views count as one visitor, and stops being linkable to them tomorrow.
   */
  visitor?: string | null;
  updatedAt: string;
  createdAt: string;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "access-links".
 */
export interface AccessLink {
  id: number;
  tokenHash: string;
  email: string;
  /**
   * Ids of the listings this link opens.
   */
  schools:
    | {
        [k: string]: unknown;
      }
    | unknown[]
    | string
    | number
    | boolean
    | null;
  expiresAt: string;
  purpose: 'outreach' | 'requested';
  lastUsedAt?: string | null;
  updatedAt: string;
  createdAt: string;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "payload-kv".
 */
export interface PayloadKv {
  id: number;
  key: string;
  data:
    | {
        [k: string]: unknown;
      }
    | unknown[]
    | string
    | number
    | boolean
    | null;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "payload-locked-documents".
 */
export interface PayloadLockedDocument {
  id: number;
  document?:
    | ({
        relationTo: 'schools';
        value: string | School;
      } | null)
    | ({
        relationTo: 'school-submissions';
        value: number | SchoolSubmission;
      } | null)
    | ({
        relationTo: 'school-contacts';
        value: number | SchoolContact;
      } | null)
    | ({
        relationTo: 'users';
        value: number | User;
      } | null)
    | ({
        relationTo: 'events';
        value: number | Event;
      } | null)
    | ({
        relationTo: 'access-links';
        value: number | AccessLink;
      } | null);
  globalSlug?: string | null;
  user: {
    relationTo: 'users';
    value: number | User;
  };
  updatedAt: string;
  createdAt: string;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "payload-preferences".
 */
export interface PayloadPreference {
  id: number;
  user: {
    relationTo: 'users';
    value: number | User;
  };
  key?: string | null;
  value?:
    | {
        [k: string]: unknown;
      }
    | unknown[]
    | string
    | number
    | boolean
    | null;
  updatedAt: string;
  createdAt: string;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "payload-migrations".
 */
export interface PayloadMigration {
  id: number;
  name?: string | null;
  batch?: number | null;
  updatedAt: string;
  createdAt: string;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "schools_select".
 */
export interface SchoolsSelect<T extends boolean = true> {
  id?: T;
  name?: T;
  slug?: T;
  level?: T;
  tagline?: T;
  summary?: T;
  scope?: T;
  yearFounded?: T;
  curricula?: T;
  faith?: T;
  state?: T;
  area?: T;
  address?: T;
  busStop?: T;
  phone?: T;
  email?: T;
  admissionsOfficer?: T;
  admissionsRole?: T;
  website?: T;
  fee?:
    | T
    | {
        label?: T;
        min?: T;
        max?: T;
      };
  feeItems?:
    | T
    | {
        label?: T;
        amount?: T;
        id?: T;
      };
  scholarship?: T;
  siblingsDiscount?: T;
  admissionForm?: T;
  day?: T;
  boarding?: T;
  maxClassSize?: T;
  facilities?: T;
  activities?: T;
  clubs?: T;
  images?:
    | T
    | {
        logo?: T;
        gallery?:
          | T
          | {
              full?: T;
              thumb?: T;
              id?: T;
            };
      };
  featured?: T;
  verified?: T;
  updatedAt?: T;
  createdAt?: T;
  _status?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "school-submissions_select".
 */
export interface SchoolSubmissionsSelect<T extends boolean = true> {
  status?: T;
  reviewNote?: T;
  kind?: T;
  school?: T;
  schoolName?: T;
  schoolSlug?: T;
  contactName?: T;
  contactRole?: T;
  contactEmail?: T;
  message?: T;
  changes?: T;
  before?: T;
  reviewedBy?: T;
  reviewedAt?: T;
  updatedAt?: T;
  createdAt?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "school-contacts_select".
 */
export interface SchoolContactsSelect<T extends boolean = true> {
  school?: T;
  name?: T;
  email?: T;
  status?: T;
  optedOut?: T;
  sends?: T;
  firstSentAt?: T;
  lastSentAt?: T;
  openedAt?: T;
  submittedAt?: T;
  updatedAt?: T;
  createdAt?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "users_select".
 */
export interface UsersSelect<T extends boolean = true> {
  name?: T;
  role?: T;
  updatedAt?: T;
  createdAt?: T;
  email?: T;
  resetPasswordToken?: T;
  resetPasswordExpiration?: T;
  salt?: T;
  hash?: T;
  loginAttempts?: T;
  lockUntil?: T;
  sessions?:
    | T
    | {
        id?: T;
        createdAt?: T;
        expiresAt?: T;
      };
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "events_select".
 */
export interface EventsSelect<T extends boolean = true> {
  type?: T;
  path?: T;
  slug?: T;
  query?: T;
  filters?: T;
  results?: T;
  referrer?: T;
  device?: T;
  visitor?: T;
  updatedAt?: T;
  createdAt?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "access-links_select".
 */
export interface AccessLinksSelect<T extends boolean = true> {
  tokenHash?: T;
  email?: T;
  schools?: T;
  expiresAt?: T;
  purpose?: T;
  lastUsedAt?: T;
  updatedAt?: T;
  createdAt?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "payload-kv_select".
 */
export interface PayloadKvSelect<T extends boolean = true> {
  key?: T;
  data?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "payload-locked-documents_select".
 */
export interface PayloadLockedDocumentsSelect<T extends boolean = true> {
  document?: T;
  globalSlug?: T;
  user?: T;
  updatedAt?: T;
  createdAt?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "payload-preferences_select".
 */
export interface PayloadPreferencesSelect<T extends boolean = true> {
  user?: T;
  key?: T;
  value?: T;
  updatedAt?: T;
  createdAt?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "payload-migrations_select".
 */
export interface PayloadMigrationsSelect<T extends boolean = true> {
  name?: T;
  batch?: T;
  updatedAt?: T;
  createdAt?: T;
}
/**
 * The email schools receive. Placeholders: {school} is the school's name and {location} its town and state. A paragraph that is just {listing} becomes a panel linking to each of the school's pages on Eduplana; one that is just {link} becomes the button to their private edit page. The logo, and a footer saying why they received it with an unsubscribe link, are always added.
 *
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "outreach-settings".
 */
export interface OutreachSetting {
  id: number;
  /**
   * Shown as the sender.
   */
  fromName: string;
  /**
   * Must be an @eduplana.org address. Replies come back here.
   */
  fromEmail: string;
  subject: string;
  body: string;
  generalSubject: string;
  generalBody: string;
  /**
   * Most emails sent in any 24 hours. Resend's free plan allows 100 a day across everything, including the Gmail send-as addresses, so this leaves headroom. A new domain that sends hundreds at once gets marked as spam — ramp up slowly.
   */
  dailyLimit: number;
  updatedAt?: string | null;
  createdAt?: string | null;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "outreach-settings_select".
 */
export interface OutreachSettingsSelect<T extends boolean = true> {
  fromName?: T;
  fromEmail?: T;
  subject?: T;
  body?: T;
  generalSubject?: T;
  generalBody?: T;
  dailyLimit?: T;
  updatedAt?: T;
  createdAt?: T;
  globalType?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "collections_widget".
 */
export interface CollectionsWidget {
  data?: {
    [k: string]: unknown;
  };
  width: 'full';
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "auth".
 */
export interface Auth {
  [k: string]: unknown;
}


declare module 'payload' {
  export interface GeneratedTypes extends Config {}
}